# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ios-test' do
  
  pod 'AFNetworking', '~> 2.5'

end

target 'ios-testTests' do

end

target 'ios-testUITests' do

end

